
variables:
  APPLICATION_NAME: "hoymiles-solar"
  ARTIFACT_NAME: "hoymiles-solar"
  DOCKER_REGISTRY_URL: hub.docker.com/banny310
  MAVEN_LOCAL_REPO: /projects-cache/.m2/
  MAVEN_OPTS: '-DXmx1024m -DXX:MaxPermSize=256m'
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end"
  BUILD_FROM_AMD64: "adoptopenjdk/openjdk11:x86_64-ubuntu-jdk-11.0.14.1_1-slim"
  BUILD_FROM_AARCH64: "adoptopenjdk/openjdk11:aarch64-ubuntu-jdk-11.0.14.1_1-slim"
  BUILD_FROM_ARMV7: "adoptopenjdk/openjdk11:armv7l-ubuntu-jdk-11.0.14.1_1-slim"

build-artifact:
  image: maven:3-eclipse-temurin-11
  stage: build
  script:
    - mvn clean compile assembly:single ${MAVEN_CLI_OPTS}
    - BUILD_VERSION=`git describe --abbrev=0 --tags 2>/dev/null || echo "0.1.0"`
    - mkdir -p artifacts
    - cp target/hoymiles-solar-1.0-SNAPSHOT-jar-with-dependencies.jar artifacts/${ARTIFACT_NAME}-${BUILD_VERSION}.jar -v || exit $?
  tags:
    - docker
  artifacts:
    paths:
      - artifacts
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF}"
    expire_in: 1 week
  only:
    refs:
      - tags

build-docker:
  image: docker:19.03.12
  stage: deploy
  dependencies:
    - build-artifact
  script:
    - apk update && apk add git
    - BUILD_VERSION=`git describe --abbrev=0 --tags 2>/dev/null || echo "0.1.0"`
    - docker build --build-arg JAR_FILE=artifacts/${APPLICATION_NAME}-${BUILD_VERSION}.jar --build-arg BUILD_FROM=${BUILD_FROM_ARMV7} --build-arg BUILD_ARCH=armv7 --platform linux/armv7 --tag banny310/hoymiles-solar-armv7:latest --file docker/Dockerfile .
    - docker build --build-arg JAR_FILE=artifacts/${APPLICATION_NAME}-${BUILD_VERSION}.jar --build-arg BUILD_FROM=${BUILD_FROM_AMD64} --build-arg BUILD_ARCH=amd64 --platform linux/amd64 --tag banny310/hoymiles-solar-amd64:latest --file docker/Dockerfile .
    - docker build --build-arg JAR_FILE=artifacts/${APPLICATION_NAME}-${BUILD_VERSION}.jar --build-arg BUILD_FROM=${BUILD_FROM_AARCH64} --build-arg BUILD_ARCH=aarch64 --platform linux/aarch64 --tag banny310/hoymiles-solar-aarch64:latest --file docker/Dockerfile .
  tags:
    - docker
  only:
    refs:
      - tags
