
variables:
  APPLICATION_NAME: "hoymiles-dtu"
  ARTIFACT_NAME: "hoymiles-dtu"
  DOCKER_REGISTRY_URL: "hub.docker.com/banny310"
  DOCKER_REGISTRY_USERNAME: "banny310"
  MAVEN_LOCAL_REPO: "/projects-cache/.m2/"
  MAVEN_OPTS: '-DXmx1024m -DXX:MaxPermSize=256m'
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots --errors --fail-at-end"

build-artifact:
  image:
    name: maven:3.8.3-eclipse-temurin-11
    #entrypoint: [ '/bin/sh', '-c' ]
  stage: build
  script:
    - mvn clean compile assembly:single ${MAVEN_CLI_OPTS}
    - BUILD_VERSION=`git describe --abbrev=0 --tags 2>/dev/null || echo "0.1.0"`
    - mkdir -p artifacts
    - cp target/hoymiles-dtu-1.0-SNAPSHOT-jar-with-dependencies.jar artifacts/${ARTIFACT_NAME}-${BUILD_VERSION}.jar -v || exit $?
  tags:
    - docker
  artifacts:
    paths:
      - artifacts
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF}"
    expire_in: 1 week
#  only:
#    refs:
#      - tags

.build-docker-template:
  image: docker:20.10.12
  stage: deploy
  dependencies:
    - build-artifact
  before_script:
    - apk update && apk add git
    - BUILD_VERSION=`git describe --abbrev=0 --tags 2>/dev/null || echo "0.1.0"`
  script:
    - docker build --build-arg JAR_FILE=artifacts/${APPLICATION_NAME}-${BUILD_VERSION}.jar --build-arg BUILD_FROM=${BUILD_FROM} --build-arg BUILD_ARCH=${BUILD_ARCH} --platform ${DOCKER_PLATFORM} --tag ${DOCKER_TAG}:latest --tag ${DOCKER_TAG}:${BUILD_VERSION} --file docker/Dockerfile .
    - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${HUBDOCKER_PASSWORD}
    - docker push banny310/hoymiles-dtu-armv7:${BUILD_VERSION}
    - docker push banny310/hoymiles-dtu-armv7:latest
  tags:
    - docker
  only:
    refs:
      - tags

build-docker-armv7:
  extends: .build-docker-template
  variables:
    BUILD_ARCH: "armv7"
    BUILD_FROM: "adoptopenjdk/openjdk11:armv7l-ubuntu-jdk-11.0.15_10-slim"
    DOCKER_PLATFORM: "linux/armv7"
    DOCKER_TAG: "banny310/hoymiles-dtu-armv7"

build-docker-amd64:
  extends: .build-docker-template
  variables:
    BUILD_ARCH: "amd64"
    BUILD_FROM: "adoptopenjdk/openjdk11:x86_64-ubuntu-jdk-11.0.15_10-slim"
    DOCKER_PLATFORM: "linux/amd64"
    DOCKER_TAG: "banny310/hoymiles-dtu-amd64"

build-docker-aarch64:
  extends: .build-docker-template
  variables:
    BUILD_ARCH: "aarch64"
    BUILD_FROM: "adoptopenjdk/openjdk11:aarch64-ubuntu-jdk-11.0.15_10-slim"
    DOCKER_PLATFORM: "linux/aarch64"
    DOCKER_TAG: "banny310/hoymiles-dtu-aarch64"
